system:
    default:
        field_templates:
            - {template: "@NetgenMetadata/field/view/xrowmetadata.html.twig", priority: 0}
        fielddefinition_settings_templates:
            - {template: "@NetgenMetadata/field_definition/view/xrowmetadata.html.twig", priority: 0}
