parameters:
    ezpublish.fieldType.xrowmetadata.class: Netgen\Bundle\MetadataBundle\Core\FieldType\Metadata\Type
    ezpublish.fieldType.indexable.xrowmetadata.class: eZ\Publish\Core\FieldType\Unindexed

services:
    ezpublish.fieldType.xrowmetadata:
        class: "%ezpublish.fieldType.xrowmetadata.class%"
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}

    ezpublish.fieldType.indexable.xrowmetadata:
        class: "%ezpublish.fieldType.indexable.xrowmetadata.class%"
        tags:
            - {name: ezpublish.fieldType.indexable, alias: xrowmetadata}
