services:
    netgen_metadata.field_type:
        class: Netgen\Bundle\MetadataBundle\Core\FieldType\Metadata\Type
        public: true
        parent: ezpublish.fieldType
        tags:
            - { name: ezpublish.fieldType, alias: xrowmetadata }

    netgen_metadata.field_type.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        public: false
        tags:
            - { name: ezpublish.fieldType.indexable, alias: xrowmetadata }
