parameters:
    ezpublish.fieldType.metadata.class: Netgen\Bundle\MetadataBundle\Core\FieldType\Metadata\Type

services:
    ezpublish.fieldType.metadata:
        class: %ezpublish.fieldType.metadata.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}