parameters:
    ezpublish.fieldType.xrowmetadata.converter.class: Netgen\Bundle\MetadataBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\MetadataConverter

services:
    ezpublish.fieldType.xrowmetadata.converter:
        class: %ezpublish.fieldType.xrowmetadata.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata, lazy: true, callback: "::create"}
