services:
    netgen_metadata.field_type:
        class: Netgen\Bundle\MetadataBundle\Core\FieldType\Metadata\Type
        parent: Ibexa\Core\FieldType\FieldType
        tags:
            - { name: ibexa.field_type, alias: xrowmetadata }

    netgen_metadata.field_type.indexable:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: xrowmetadata }

    netgen_metadata.field_type.form_mapper:
        class: Netgen\Bundle\MetadataBundle\Core\FieldType\Metadata\FormMapper
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: xrowmetadata }

    netgen_metadata.field_type.legacy.converter:
        class: Netgen\Bundle\MetadataBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\MetadataConverter
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: xrowmetadata }

    netgen_metadata.form.metadata_field:
        class: Netgen\Bundle\MetadataBundle\Form\Type\FieldType\MetadataFieldType
        arguments:
            - "@netgen_metadata.field_type"
        tags:
            - { name: form.type }
