services:
    netgen_metadata.field_type.legacy.converter:
        class: Netgen\Bundle\MetadataBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\MetadataConverter
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: xrowmetadata }
