services:
    netgen_metadata.field_type.legacy.converter:
        class: Netgen\Bundle\MetadataBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\MetadataConverter
        public: false
        tags:
            - { name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata, lazy: true, callback: "::create" }
